insert into brand(id, name) values(1, 'AlfaRomeo');
insert into brand(id, name) values(2, 'Audi');
insert into brand(id, name) values(3, 'BAW');
insert into brand(id, name) values(4, 'BMW');
insert into brand(id, name) values(5, 'Caterpillar');
insert into brand(id, name) values(6, 'CF Moto');
insert into brand(id, name) values(7, 'Chevrolet');
insert into brand(id, name) values(8, 'Citroen');
insert into brand(id, name) values(9, 'Daewoo');
insert into brand(id, name) values(10, 'DAF');
insert into brand(id, name) values(11, 'DIMEX');
insert into brand(id, name) values(12, 'DongFeng');
insert into brand(id, name) values(13, 'FAW');
insert into brand(id, name) values(14, 'Fiat');
insert into brand(id, name) values(15, 'Ford');
insert into brand(id, name) values(16, 'Foton');
insert into brand(id, name) values(17, 'Howo');
insert into brand(id, name) values(18, 'Huebner');
insert into brand(id, name) values(19, 'Huta Stalowa Wola S.A. (HSW)');
insert into brand(id, name) values(20, 'Honda');
insert into brand(id, name) values(21, 'Hyundai');
insert into brand(id, name) values(22, 'Isuzu');
insert into brand(id, name) values(23, 'Jaguar');
insert into brand(id, name) values(24, 'Jeep');
insert into brand(id, name) values(25, 'Kia');
insert into brand(id, name) values(26, 'LandRover');
insert into brand(id, name) values(27, 'LongGong');
insert into brand(id, name) values(28, 'Lexus');
insert into brand(id, name) values(29, 'Man');
insert into brand(id, name) values(30, 'Mazda');
insert into brand(id, name) values(31, 'Mercedes Benz');
insert into brand(id, name) values(32, 'Mitsubishi');
insert into brand(id, name) values(33, 'Nissan');
insert into brand(id, name) values(34, 'Opel');
insert into brand(id, name) values(35, 'Peugeot');
insert into brand(id, name) values(36, 'Porsche');
insert into brand(id, name) values(37, 'Renault');
insert into brand(id, name) values(38, 'Rover');
insert into brand(id, name) values(39, 'Saab');
insert into brand(id, name) values(40, 'Scania');
insert into brand(id, name) values(41, 'Suzuki Moto');
insert into brand(id, name) values(42, 'Shaanxi');
insert into brand(id, name) values(43, 'Skoda');
insert into brand(id, name) values(44, 'SsangYong');
insert into brand(id, name) values(45, 'Subaru');
insert into brand(id, name) values(46, 'Suzuki');
insert into brand(id, name) values(47, 'Toyota');
insert into brand(id, name) values(48, 'Volkswagen');
insert into brand(id, name) values(49, 'Volvo');
insert into brand(id, name) values(50, 'Way Industry');
insert into brand(id, name) values(51, 'Xiamen');
insert into brand(id, name) values(52, 'ZF');
insert into brand(id, name) values(53, 'АЗЛК');
insert into brand(id, name) values(54, 'ВАЗ');
insert into brand(id, name) values(55, 'ГАЗ');
insert into brand(id, name) values(56, 'ЗАЗ');
insert into brand(id, name) values(57, 'ИЖ');
insert into brand(id, name) values(58, 'ЧМЗАП');
insert into brand(id, name) values(59, 'ЛуАЗ');
insert into brand(id, name) values(60, 'РАФ');
insert into brand(id, name) values(61, 'УАЗ');
insert into brand(id, name) values(62, 'Автокомпонент Плюс');
insert into brand(id, name) values(63, 'БелАЗ');
insert into brand(id, name) values(64, 'Урал');
insert into brand(id, name) values(65, 'ЗИЛ');
insert into brand(id, name) values(66, 'КАЗ');
insert into brand(id, name) values(67, 'КамАЗ');
insert into brand(id, name) values(68, 'КРАЗ');
insert into brand(id, name) values(69, 'МАЗ');
insert into brand(id, name) values(70, 'Мадара');
insert into brand(id, name) values(71, 'МЗКТ');
insert into brand(id, name) values(72, 'МоАЗ');
insert into brand(id, name) values(73, 'НефАЗ');
insert into brand(id, name) values(74, 'СЗАП');
insert into brand(id, name) values(75, 'Студебеккер');
insert into brand(id, name) values(76, 'ТАТРА');
insert into brand(id, name) values(77, 'Тонар');


