insert into color(id, name) values(1, 'Абрикос (серебристо-светло оранжевый)');
insert into color(id, name) values(2, 'Авантюрин (серебристо-чёрный)');
insert into color(id, name) values(3, 'Айсберг (белая двухслойная)');
insert into color(id, name) values(4, 'Акапулько (ярко-жёлтый)');
insert into color(id, name) values(5, 'Аквамарин (серебристый сине-зелёный)');
insert into color(id, name) values(6, 'Аккорд (серебристо-коричневый)');
insert into color(id, name) values(7, 'Аллигатор (оливково-зелёный)');
insert into color(id, name) values(8, 'Алмазное серебро (серебристый, ИЖ)');
insert into color(id, name) values(9, 'Альпийский снег (белый металлик)');
insert into color(id, name) values(10, 'Альтаир (серебристый светло-серый)');
insert into color(id, name) values(11, 'Амазонка (ярко-зелёный)');
insert into color(id, name) values(12, 'Аметист (серебристый фиолетовый)');
insert into color(id, name) values(13, 'Амулет (серебристо-тёмно-зелёный)');
insert into color(id, name) values(14, 'Андриатика (голубой)');
insert into color(id, name) values(15, 'Антарес (тёмно-вишнёвый)');
insert into color(id, name) values(16, 'Антилопа (серебристо-бежевый)');
insert into color(id, name) values(17, 'Апатия (серебристый оранжевый)');
insert into color(id, name) values(18, 'Аспарагус (серебристо-зелёный)');
insert into color(id, name) values(19, 'Астероид (тёмно-сине-зелёный)');
insert into color(id, name) values(20, 'Атлантика (светло-синий)');
insert into color(id, name) values(21, 'Аустер (светло-серый, GM)');
insert into color(id, name) values(22, 'Афалина (серебристо-зелёно-голубой)');
insert into color(id, name) values(23, 'Аэлита (бежевый)');
insert into color(id, name) values(24, 'Базальт (серо-чёрный)');
insert into color(id, name) values(25, 'Баклажан (тёмно-фиолетовый)');
insert into color(id, name) values(26, 'Балтика (тёмно-сине-зелёный)');
insert into color(id, name) values(27, 'Бальзам (зелёный)');
insert into color(id, name) values(28, 'Бархан (бежевый)');
insert into color(id, name) values(29, 'Бежевый (бежевый)');
insert into color(id, name) values(30, 'Белое облако (белый)');
insert into color(id, name) values(31, 'Белый (белый)');
insert into color(id, name) values(32, 'Бергамот (серебристо-зелёный)');
insert into color(id, name) values(33, 'Борнео (серебристо-тёмно серый)');
insert into color(id, name) values(34, 'Боровница (серебристо-серо-синий)');
insert into color(id, name) values(35, 'Бриз (зелёно-голубой)');
insert into color(id, name) values(36, 'Бронзовый век (бежево-коричневый)');
insert into color(id, name) values(37, 'Бургундия (красный металлик)');
insert into color(id, name) values(38, 'Вавилон (металлик серо-бежевый)');
insert into color(id, name) values(39, 'Валентина (серо-фиолетовый)');
insert into color(id, name) values(40, 'Валюта (серо-зелёный)');
insert into color(id, name) values(41, 'Венера (тёмно-красный)');
insert into color(id, name) values(42, 'Викинг (тёмно-серый)');
insert into color(id, name) values(43, 'Виктория (серебристый ярко-красный)');
insert into color(id, name) values(44, 'Вишнёвый сад (тёмно-серебристо-красный)');
insert into color(id, name) values(45, 'Вишня (тёмно-бордовый)');
insert into color(id, name) values(46, 'Водолей (серо-зелёный)');
insert into color(id, name) values(47, 'Галактика (тёмно-фиолетовый)');
insert into color(id, name) values(48, 'Гейзер (серо-голубой)');
insert into color(id, name) values(49, 'Голубой (голубой)');
insert into color(id, name) values(50, 'Гранат (тёмно-бордовый)');
insert into color(id, name) values(51, 'Гранта (серо-синий)');
insert into color(id, name) values(52, 'Дефиле (серебристо-серо-коричневый)');
insert into color(id, name) values(53, 'Джем (оранжево-коричневый)');
insert into color(id, name) values(54, 'Дипломат (синий)');
insert into color(id, name) values(55, 'Дыня (серебристо-жёлтый)');
insert into color(id, name) values(56, 'Дюшес (серебристо-молочно-зелёный)');
insert into color(id, name) values(57, 'Жасмин (бело-жёлтый)');
insert into color(id, name) values(58, 'Жёлтый-такси (ярко-жёлтый)');
insert into color(id, name) values(59, 'Жемчуг (серебристо-бело-молочный)');
insert into color(id, name) values(60, 'Жимолость (серо-синий)');
insert into color(id, name) values(61, 'Защитный (зелёный)');
insert into color(id, name) values(62, 'Звёздная Пыль (бежево-сиреневый)');
insert into color(id, name) values(63, 'Зелёный сад (тёмно-зелёный)');
insert into color(id, name) values(64, 'Зелёный (зелёный)');
insert into color(id, name) values(65, 'Зелёный Авокадо (тёмно-зелёный, ИЖ)');
insert into color(id, name) values(66, 'Золотая звезда (бежево-золотистый, GM)');
insert into color(id, name) values(67, 'Золотой лист (золотистый тёмно-зелёный)');
insert into color(id, name) values(68, 'Золотая Нива (серебристо-жёлто-зелёный)');
insert into color(id, name) values(69, 'Золотисто-бежевый (золотисто-бежевый, ИЖ)');
insert into color(id, name) values(70, 'Золото Инков (золотистый тёмно-зелёный)');
insert into color(id, name) values(71, 'Игуана (серебристо-ярко-зелёный)');
insert into color(id, name) values(72, 'Изабелла (тёмно-филетовый)');
insert into color(id, name) values(73, 'Изумруд (серебристо-зелёный)');
insert into color(id, name) values(74, 'Индиго (тёмно-синий)');
insert into color(id, name) values(75, 'Ирис (фиолетовый)');
insert into color(id, name) values(76, 'Искра (красный)');
insert into color(id, name) values(77, 'Каберне (тёмно-вишнёвый)');
insert into color(id, name) values(78, 'Кайман (тёмно-зелёный)');
insert into color(id, name) values(79, 'Калина (ярко-красный)');
insert into color(id, name) values(80, 'Калифорнийский Мак (золотисто-красный)');
insert into color(id, name) values(81, 'Капри (тёмно-сине-зелёный)');
insert into color(id, name) values(82, 'Капучино (светлый серо-бежевый)');
insert into color(id, name) values(83, 'Кардинал (ярко-красный)');
insert into color(id, name) values(84, 'Кармен (красный)');
insert into color(id, name) values(85, 'Кварц (тёмно-серый)');
insert into color(id, name) values(86, 'Кедр (серо-зелёный)');
insert into color(id, name) values(87, 'Кентавр (тёмно-зелёный)');
insert into color(id, name) values(88, 'Колумбийская зелень (золотисто-оливковый)');
insert into color(id, name) values(89, 'Коралл (серебристый тёмно-красный)');
insert into color(id, name) values(90, 'Кориандр (золотисто-коричневый)');
insert into color(id, name) values(91, 'Корица (коричневый)');
insert into color(id, name) values(92, 'Корсика (серебристый болотно-зелёный)');
insert into color(id, name) values(93, 'Космос (чёрный)');
insert into color(id, name) values(94, 'Красный перец (серебристо-вишнёвый, ИЖ)');
insert into color(id, name) values(95, 'Красный Порту (вишнёвый, ИЖ)');
insert into color(id, name) values(96, 'Кристалл (светло-серый)');
insert into color(id, name) values(97, 'Кубок (красный)');
insert into color(id, name) values(98, 'Ла-манш (серебристо-фиолетовый)');
insert into color(id, name) values(99, 'Лаванда (серебристо-коричневый)');
insert into color(id, name) values(100, 'Лагуна (серебристо-синий)');
insert into color(id, name) values(101, 'Ладога (серебристо-голубой)');
insert into color(id, name) values(102, 'Лазурит (фиолетово-синий)');
insert into color(id, name) values(103, 'Лазурно-синий (серебристый тёмно-синий)');
insert into color(id, name) values(104, 'Лазурь (синий)');
insert into color(id, name) values(105, 'Лайм (лайм, LADA)');
insert into color(id, name) values(106, 'Ламинария (зелёный)');
insert into color(id, name) values(107, 'Ледниковый (белый)');
insert into color(id, name) values(108, 'Ледяной (голубой)');
insert into color(id, name) values(109, 'Лунный Свет (светло-голубой)');
insert into color(id, name) values(110, 'Магеллан (тёмно-синий)');
insert into color(id, name) values(111, 'Магия (серебристо-ярко-фиолетовый)');
insert into color(id, name) values(112, 'Магма (оранжевый)');
insert into color(id, name) values(113, 'Майя (серебристый тёмно-бордовый)');
insert into color(id, name) values(114, 'Мальборо (красный металлик)');
insert into color(id, name) values(115, 'Медео (голубой)');
insert into color(id, name) values(116, 'Медовый (желто-золотой)');
insert into color(id, name) values(117, 'Меридиан (зелёный)');
insert into color(id, name) values(118, 'Мерцающий синий (серебристо-тёмно-синий, ИЖ)');
insert into color(id, name) values(119, 'Миндаль (серебристо-бежево-розовый)');
insert into color(id, name) values(120, 'Мираж (серебристый-желто-зелёный)');
insert into color(id, name) values(121, 'Млечный Путь (серебристо-серо-графитовый)');
insert into color(id, name) values(122, 'Мокрый асфальт (серебристый стальной)');
insert into color(id, name) values(123, 'Монте-карло (ярко-синий)');
insert into color(id, name) values(124, 'Морская Пучина (тёмно-зелёный)');
insert into color(id, name) values(125, 'Мулен Руж (ярко-фиолетовый)');
insert into color(id, name) values(126, 'Мурена (сине-зелёный)');
insert into color(id, name) values(127, 'Мускари (мускари)');
insert into color(id, name) values(128, 'Мускат (серебристо-серо-золотистый)');
insert into color(id, name) values(129, 'Нарцисс (жёлтый)');
insert into color(id, name) values(130, 'Наутилус (тёмно-зелёный)');
insert into color(id, name) values(131, 'Невада (серебристо-серо-бежевый)');
insert into color(id, name) values(132, 'Нептун (серебристо-тёмно-серо-синий)');
insert into color(id, name) values(133, 'Несси (тёмно-зелёный)');
insert into color(id, name) values(134, 'Нефертити (серебристый-бежевый)');
insert into color(id, name) values(135, 'Ниагара (серебристо-серо-голубоватый)');
insert into color(id, name) values(136, 'Ницца (сине-зелёный)');
insert into color(id, name) values(137, 'Одиссей (серо-синий)');
insert into color(id, name) values(138, 'Озеро Тахо (тёмно-серо-зелёный, УАЗ)');
insert into color(id, name) values(139, 'Океан (тёмно-синий)');
insert into color(id, name) values(140, 'Оливин (золотисто-зелёный)');
insert into color(id, name) values(141, 'Оливковый (желто-зелёный)');
insert into color(id, name) values(142, 'Олимпия (ярко-синий, GM)');
insert into color(id, name) values(143, 'Опал (серебристо-голубоватый)');
insert into color(id, name) values(144, 'Орион (средне-стальной)');
insert into color(id, name) values(145, 'Орхидея (серебристо-бежевый)');
insert into color(id, name) values(146, 'Осока (зелено-голубой)');
insert into color(id, name) values(147, 'Папирус (серебристо-серо-зеленоватый)');
insert into color(id, name) values(148, 'Паприка (серебристо-красно-оранжевый)');
insert into color(id, name) values(149, 'Персей (тёмно-синий)');
insert into color(id, name) values(150, 'Петергоф (серо-зеленоватый)');
insert into color(id, name) values(151, 'Пирано (красно-коричневый)');
insert into color(id, name) values(152, 'Пицунда (зелено-синий)');
insert into color(id, name) values(153, 'Платина (серебристо-бежевый)');
insert into color(id, name) values(154, 'Полюс Мира (серо-коричневый)');
insert into color(id, name) values(155, 'Портвейн (тёмно-вишнёвый металлик)');
insert into color(id, name) values(156, 'Посейдон (тёмно-синий)');
insert into color(id, name) values(157, 'Премьер (ярко-жёлтый)');
insert into color(id, name) values(158, 'Прерия (серебристо-серо-зелёный)');
insert into color(id, name) values(159, 'Престиж (серебристо-тёмно-синий)');
insert into color(id, name) values(160, 'Приз (серебристо-бежевый)');
insert into color(id, name) values(161, 'Примула (светло-жёлтый)');
insert into color(id, name) values(162, 'Рапсодия (серебристо-ярко-синий)');
insert into color(id, name) values(163, 'Регата (серебристо-тёмно-синий)');
insert into color(id, name) values(164, 'Реклама (ярко-красный)');
insert into color(id, name) values(165, 'Ривьера (сине-фиолетовый)');
insert into color(id, name) values(166, 'Рислинг (серебристо-бледно-серый)');
insert into color(id, name) values(167, 'Ричмо (тёмно-коричневый, УАЗ)');
insert into color(id, name) values(168, 'Робин Гуд (тёмно-зелёный)');
insert into color(id, name) values(169, 'Романс (тёмно-красный)');
insert into color(id, name) values(170, 'Рубин (красный)');
insert into color(id, name) values(171, 'Садко (тёмно-голубой)');
insert into color(id, name) values(172, 'Салатовый (салатовый)');
insert into color(id, name) values(173, 'Сан-тропе (ярко-синий)');
insert into color(id, name) values(174, 'Сандал (бежево-красный)');
insert into color(id, name) values(175, 'Сапфир (серебристый сине-фиолетовый)');
insert into color(id, name) values(176, 'Сафари (светло-бежевый)');
insert into color(id, name) values(177, 'Светло-серый (светло-серый)');
insert into color(id, name) values(178, 'Серебристая ива (серебристый-зеленовато-серый)');
insert into color(id, name) values(179, 'Серебристый (серебристый)');
insert into color(id, name) values(180, 'Серо-бежевый (серо-бежевый)');
insert into color(id, name) values(181, 'Серо-белый (серо-белый)');
insert into color(id, name) values(182, 'Серо-голубой (серо-голубой)');
insert into color(id, name) values(183, 'Серо-зелёный (серо-зелёный)');
insert into color(id, name) values(184, 'Серое олово (серый серебристый, ИЖ)');
insert into color(id, name) values(185, 'Серый базальт (серо-бежевый)');
insert into color(id, name) values(186, 'Синий калипсо (тёмно-синий, ИЖ)');
insert into color(id, name) values(187, 'Синяя полночь (синий)');
insert into color(id, name) values(188, 'Сирень (светло-фиолетовый)');
insert into color(id, name) values(189, 'Сириус (серо-синий)');
insert into color(id, name) values(190, 'Слива (серебристо-ярко-синий)');
insert into color(id, name) values(191, 'Сливочно-белый (сливочно-белый)');
insert into color(id, name) values(192, 'Слоновая Кость (бежево-жёлтый)');
insert into color(id, name) values(193, 'Снежная Королева (серебристый)');
insert into color(id, name) values(194, 'Снежно-белый (снежно-белый)');
insert into color(id, name) values(195, 'Совиньон (серебристо-серый)');
insert into color(id, name) values(196, 'Солярис (тёмно коричневый)');
insert into color(id, name) values(197, 'Сочи (серебристо-серо-зеленоватый)');
insert into color(id, name) values(198, 'Табачный (серебристый коричнево-зелёный)');
insert into color(id, name) values(199, 'Талая Вода (светло-серый)');
insert into color(id, name) values(200, 'Тёмно-бежевый (тёмно-бежевый)');
insert into color(id, name) values(201, 'Тёмно-коричневый (тёмно-коричневый)');
insert into color(id, name) values(202, 'Тёмно-серый (тёмно-серый)');
insert into color(id, name) values(203, 'Тёмно-синий (тёмно-синий)');
insert into color(id, name) values(204, 'Тёмно-синий (оттенок тёмно-синего)');
insert into color(id, name) values(205, 'Тополиный пух (серый)');
insert into color(id, name) values(206, 'Торнадо (красный)');
insert into color(id, name) values(207, 'Триумф (серебристо-красный)');
insert into color(id, name) values(208, 'Тундра (серебристо-зеленоватый)');
insert into color(id, name) values(209, 'Ультрамарин (сине-зелёный, ИЖ)');
insert into color(id, name) values(210, 'Успех (оранжевый)');
insert into color(id, name) values(211, 'Феерия (ярко-красный, GM)');
insert into color(id, name) values(212, 'Феникс (чёрный)');
insert into color(id, name) values(213, 'Фея (серебристо-сиреневый)');
insert into color(id, name) values(214, 'Франкония (тёмно-вишнёво-малиновый)');
insert into color(id, name) values(215, 'Фрегат (цвет морской волны)');
insert into color(id, name) values(216, 'Цунами (тёмно-зелёный)');
insert into color(id, name) values(217, 'Чайная Роза (светло-жёлтый)');
insert into color(id, name) values(218, 'Чароит (серебристый тёмно-фиолетовый)');
insert into color(id, name) values(219, 'Черешня (тёмно-алый)');
insert into color(id, name) values(220, 'Чёрная Пантера (чёрный, двойная эмаль)');
insert into color(id, name) values(221, 'Черника (тёмно-синий)');
insert into color(id, name) values(222, 'Чёрный (чёрный)');
insert into color(id, name) values(223, 'Чёрный (оттенок чёрного)');
insert into color(id, name) values(224, 'Чёрный графит (серебристо-серо-графитовый, ИЖ)');
insert into color(id, name) values(225, 'Чёрный жемчуг (серебристо-коричневый)');
insert into color(id, name) values(226, 'Чёрный трюфель (чёрный)');
insert into color(id, name) values(227, 'Чёрный шоколад (тёмно-коричневый)');
insert into color(id, name) values(228, 'Электрон (тёмно-серый)');
insert into color(id, name) values(229, 'Южный крест (серо-бежевый)');
insert into color(id, name) values(230, 'Юпитер (серебристо-голубоватый)');
insert into color(id, name) values(231, 'Яшма (тёмно-вишнёвый)');